
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhishek
 */
public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form User_Home
     */
    public Admin_Home() {
        initComponents();
        jTextField4.setText(index1.id);
         jPanel11.setVisible(false);
        
              try{
       
    //       Class.forName("com.mysql.jdbc.Driver");
  //     Connection con=DriverManager.getConnection("jdbc:mysql:\\localhost:3306\scoter","root","root");
      Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");     
       
            
            
               PreparedStatement ps=con.prepareStatement("select * from vehicle");
           ResultSet rs=ps.executeQuery();
           //DefaultTableModel
           DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
           while(rs.next()){
           
            Object obj[]={rs.getString(2),rs.getString(1),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(10),rs.getString(9),rs.getString(11)}; 
         // jComboBox1.setModel((ComboBoxModel)rs.getString(2) );
            //jComboBox1.setModel(new ComboBoxModel<rs>);
         jComboBox1.addItem(rs.getString(1));
               jComboBox7.addItem(rs.getString(1));
            dtm.addRow(obj);
           }
           
           
               PreparedStatement ps1=con.prepareStatement("select * from recordtable");   
          ResultSet rs1=ps1.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm1=(DefaultTableModel)jTable2.getModel();
           while(rs1.next()){
           
             Object obj1[]={rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4),rs1.getString(5)}; 
        jComboBox2.addItem(rs1.getString(3));
            // jComboBox1.setModel((ComboBoxModel)rs.getString(2) );
             dtm1.addRow(obj1);
           } 
     
           
            PreparedStatement ps2=con.prepareStatement("select * from feedbacktable");   
          ResultSet rs2=ps2.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm2=(DefaultTableModel)jTable6.getModel();
           while(rs2.next()){
           
          Object obj3[]={rs2.getString(3),rs2.getString(1),rs2.getString(2)}; 
             dtm2.addRow(obj3);
             jComboBox4.addItem(rs2.getString(3));
             
           }
           
          
             PreparedStatement ps3=con.prepareStatement("select * from complaintable");   
          ResultSet rs3=ps3.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm3=(DefaultTableModel)jTable4.getModel();
           while(rs3.next()){
           
            Object obj3[]={rs3.getString(3),rs3.getString(1),rs3.getString(2)}; 
             dtm3.addRow(obj3);
             jComboBox3.addItem(rs3.getString(3));
             
           }
           
         
           
    PreparedStatement ps4=con.prepareStatement("select * from queriestable");   
          ResultSet rs4=ps4.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm4=(DefaultTableModel)jTable7.getModel();
           while(rs4.next()){
           
             Object obj4[]={rs4.getString(3),rs4.getString(1),rs4.getString(2)}; 
             dtm4.addRow(obj4);
             jComboBox5.addItem(rs4.getString(3));
             
           }
    
       }
       catch(Exception Ex)
       {
          Ex.printStackTrace();
       }
            
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton16 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField14 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPasswordField7 = new javax.swing.JPasswordField();
        jPasswordField6 = new javax.swing.JPasswordField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/welcome.gif"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 510, 150));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/39420.gif"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setBackground(new java.awt.Color(0, 51, 51));
        jButton20.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(204, 255, 51));
        jButton20.setText("Set Charges");
        jButton20.setToolTipText("");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 220, 40));

        jButton15.setBackground(new java.awt.Color(0, 0, 102));
        jButton15.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(204, 255, 51));
        jButton15.setText("Delet Records");
        jButton15.setToolTipText("");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 300, 40));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 153));
        jComboBox1.setForeground(new java.awt.Color(204, 255, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---select---", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 230, 40));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox7.setBackground(new java.awt.Color(0, 153, 255));
        jComboBox7.setForeground(new java.awt.Color(255, 255, 153));
        jComboBox7.setSelectedItem(jTable1);
        jPanel11.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/coin-add-icon.png"))); // NOI18N
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 50, 30));

        jButton1.setText("Save Charges");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 150, 50));

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setForeground(new java.awt.Color(153, 255, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 30));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 540, 80));

        jScrollPane1.setOpaque(false);

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 51)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_id", "Vehicle_id", "Vehicle_name", "Vehicle Number", "ManufactureDate", "contanctNumber", "Availblity time", "Avaliblity Date", "Aprox_Charges", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1170, 200));

        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, -1));

        jTabbedPane1.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/Candy-House-icon.png")), jPanel2); // NOI18N

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 0));
        jLabel10.setText("       Create new Operator");
        jLabel10.setOpaque(true);
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 390, 54));

        jLabel18.setBackground(new java.awt.Color(51, 0, 51));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Operator Name");
        jLabel18.setOpaque(true);
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, 27));

        jLabel19.setBackground(new java.awt.Color(51, 0, 51));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Password");
        jLabel19.setOpaque(true);
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, -1));

        jLabel21.setBackground(new java.awt.Color(51, 0, 51));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("conf Password");
        jLabel21.setOpaque(true);
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 30));

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 230, 27));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, -1));

        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("ADD");
        jButton5.setToolTipText("");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 105, -1));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Back");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 119, -1));

        jLabel23.setBackground(new java.awt.Color(51, 0, 51));
        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Operator_id");
        jLabel23.setOpaque(true);
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 101, 27));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel8.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 210, 30));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel8.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, -1));

        jTabbedPane1.addTab("Add Operator", new javax.swing.ImageIcon(getClass().getResource("/gif/Devices-secure-card-icon.png")), jPanel1); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---select---", " " }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 260, 40));

        jButton16.setBackground(new java.awt.Color(0, 51, 51));
        jButton16.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 51, 51));
        jButton16.setText("Delet Records");
        jButton16.setToolTipText("");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 300, 40));

        jScrollPane3.setOpaque(false);

        jTable2.setBackground(new java.awt.Color(0, 102, 153));
        jTable2.setForeground(new java.awt.Color(153, 255, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seller_id", "Coustomerid", "vehicle_id", "date And Time", "vihecle_number"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jScrollPane4.setViewportView(jScrollPane3);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 930, 300));

        jTextField14.setToolTipText("Enter The user to delet the record");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 260, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View Order", new javax.swing.ImageIcon(getClass().getResource("/Finance-Purchase-Order-icon.png")), jPanel3); // NOI18N

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(0, 51, 51));
        jButton17.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 51, 51));
        jButton17.setText("Delet Records");
        jButton17.setToolTipText("");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 300, 40));

        jLabel25.setBackground(new java.awt.Color(0, 51, 51));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 255, 0));
        jLabel25.setText("           Feedback Form");
        jLabel25.setOpaque(true);
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jScrollPane14.setOpaque(false);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feedbaack_id", "User_id", "feedback"
            }
        ));
        jScrollPane14.setViewportView(jTable6);

        jScrollPane13.setViewportView(jScrollPane14);

        jPanel10.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 720, 190));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 50));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View Feedback", new javax.swing.ImageIcon(getClass().getResource("/Messages-icon.png")), jPanel4); // NOI18N

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton18.setBackground(new java.awt.Color(0, 51, 51));
        jButton18.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 51, 51));
        jButton18.setText("Delet Records");
        jButton18.setToolTipText("");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 300, 40));

        jLabel26.setBackground(new java.awt.Color(0, 51, 51));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 255, 0));
        jLabel26.setText("          View Complain");
        jLabel26.setOpaque(true);
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jScrollPane10.setOpaque(false);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complain_id", "User_id", "complain"
            }
        ));
        jScrollPane10.setViewportView(jTable4);

        jScrollPane9.setViewportView(jScrollPane10);

        jPanel14.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 720, 190));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 50));

        jPanel5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View  Complaint", new javax.swing.ImageIcon(getClass().getResource("/msg-2-icon.png")), jPanel5); // NOI18N

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setBackground(new java.awt.Color(0, 51, 51));
        jButton19.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 51, 51));
        jButton19.setText("Delet Records");
        jButton19.setToolTipText("");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 300, 40));

        jLabel29.setBackground(new java.awt.Color(0, 51, 51));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 255, 0));
        jLabel29.setText("          View Queries ");
        jLabel29.setOpaque(true);
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 289, 54));

        jScrollPane16.setOpaque(false);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Queryid", "User_id", "Query"
            }
        ));
        jScrollPane16.setViewportView(jTable7);

        jScrollPane15.setViewportView(jScrollPane16);

        jPanel15.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 720, 190));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel15.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 50));

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View Query", new javax.swing.ImageIcon(getClass().getResource("/help-file-icon.png")), jPanel6); // NOI18N

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(0, 51, 51));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 255, 0));
        jLabel34.setText("       Change Password");
        jLabel34.setOpaque(true);
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 289, 54));

        jLabel37.setBackground(new java.awt.Color(51, 0, 51));
        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Password");
        jLabel37.setOpaque(true);
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 30));

        jLabel38.setBackground(new java.awt.Color(51, 0, 51));
        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("New Password");
        jLabel38.setOpaque(true);
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, -1));

        jLabel39.setBackground(new java.awt.Color(51, 0, 51));
        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Conf Password");
        jLabel39.setOpaque(true);
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 160, -1));

        jTextField12.setOpaque(false);
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 230, 27));

        jPasswordField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField5ActionPerformed(evt);
            }
        });
        jPanel13.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 220, 30));

        jPasswordField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField7ActionPerformed(evt);
            }
        });
        jPanel13.add(jPasswordField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 210, 30));

        jPasswordField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField6ActionPerformed(evt);
            }
        });
        jPanel13.add(jPasswordField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        jButton13.setBackground(new java.awt.Color(0, 51, 51));
        jButton13.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 51, 51));
        jButton13.setText("Update");
        jButton13.setToolTipText("");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 140, 40));

        jButton14.setBackground(new java.awt.Color(0, 51, 51));
        jButton14.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 51, 51));
        jButton14.setText("Back");
        jButton14.setToolTipText("");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 119, -1));

        jLabel40.setBackground(new java.awt.Color(51, 0, 51));
        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("User id");
        jLabel40.setOpaque(true);
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 101, 27));

        jPanel7.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 680, 440));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Change Password", new javax.swing.ImageIcon(getClass().getResource("/password-icon_1.png")), jPanel7); // NOI18N

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car-share-multiple-people-animated.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -30, 620, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Car-Share - 19 Users Infographic - Wide.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -290, 960, 940));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Help", new javax.swing.ImageIcon(getClass().getResource("/Help-icon.png")), jPanel9); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1360, 590));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/switch-turn-off-icon.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 110, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/printer-icon.png"))); // NOI18N
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 120, 70));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setForeground(new java.awt.Color(153, 255, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bikes.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1410, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

        
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
        String operator_id=jTextField4.getText();
        String operator_name=jTextField5.getText();
      
     
        String password=new String(jPasswordField1.getPassword());
        String cmfpassword=new String(jPasswordField2.getPassword());
//String password=new String(jPasswordField4.getPassword());
          if(operator_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_id field Can not be left blank ");
        
        }
       else if(operator_name.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_name Can not be left blank ");
        
        }
   else if(password.equals(""))
        {
        JOptionPane.showMessageDialog(this,"password field Can not be left blank ");
        
        }
      else if(cmfpassword.equals(""))
        {
        JOptionPane.showMessageDialog(this,"cmfpassword field Can not be left blank ");
        
        } 
   
          

// char[] ch=jPasswordField3.getPassword();
        //String password=new String(ch);
      else{ 
      try{
            
           // Class.forName("com.mysql.jdbc.Driver");
              Class.forName("com.mysql.jdbc.Driver");
            //"jdbc:mysql://localhost:3306/scoter","root","root"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into complaint_login values(?,?)");
     
        ps.setString(1,operator_id);
        ps.setString(2,password);
      
    
       ps.executeUpdate();
       
       
          
             JOptionPane.showMessageDialog(this,"New login is created" );
          
             Admin_Home inf=new Admin_Home();
             inf.setVisible(true);
             dispose();
         
             
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

     
        String operator_id=jTextField4.getText();
        String operator_name=jTextField5.getText();
      
     
        String password=new String(jPasswordField1.getPassword());
        String cmfpassword=new String(jPasswordField2.getPassword());
//String password=new String(jPasswordField4.getPassword());
          if(operator_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_id field Can not be left blank ");
        
        }
       else if(operator_name.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_name Can not be left blank ");
        
        }
   else if(password.equals(""))
        {
        JOptionPane.showMessageDialog(this,"password field Can not be left blank ");
        
        }
      else if(cmfpassword.equals(""))
        {
        JOptionPane.showMessageDialog(this,"cmfpassword field Can not be left blank ");
        
        } 
   
          

// char[] ch=jPasswordField3.getPassword();
        //String password=new String(ch);
      else{ 
      try{
            
           // Class.forName("com.mysql.jdbc.Driver");
              Class.forName("com.mysql.jdbc.Driver");
            //"jdbc:mysql://localhost:3306/scoter","root","root"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into complaint_login(?,?)");
     
        ps.setString(1,operator_id);
        ps.setString(2,password);
      
    
       ps.executeUpdate();
       
       
          
             JOptionPane.showMessageDialog(this,"New login is created" );
          
             Admin_Home inf=new Admin_Home();
             inf.setVisible(true);
             dispose();
         
             
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }
      }   

        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int output=JOptionPane.showConfirmDialog(this,"Do You Want To SignOut");
        
        if(output==0){
            index1 ref=new index1();
            ref.setVisible(true);
            dispose();
                }
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField5ActionPerformed

    private void jPasswordField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField7ActionPerformed

    private void jPasswordField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField6ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked

        String user_id=jTextField12.getText();
        String oldPass=new String(jPasswordField5.getPassword());
        String newPass=new String(jPasswordField6.getPassword());
        String confPass=new String(jPasswordField7.getPassword());

        if(user_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"id field Can't  left blank ");

        }
        else if(oldPass.equals(""))
        {
            JOptionPane.showMessageDialog(this,"oldPass field Can't left blank ");
        }
        else if(newPass.equals(""))
        {
            JOptionPane.showMessageDialog(this,"newPass field Can't left blank ");

        }
       

        else if(confPass.equals(""))
        {
            JOptionPane.showMessageDialog(this,"confPass field Can't left blank ");

        }

         else if(confPass.equals(newPass))
        {
         //   JOptionPane.showMessageDialog(this,"Confpass and new password should be same!! ");

      
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("select * from user where userid=? and password=?");

                ps.setString(1,user_id);
                ps.setString(2,oldPass);

                ResultSet rs= ps.executeQuery();

                if(rs.next())
                {
                    PreparedStatement ps1=con.prepareStatement("update user set password=? where userid=?");
                ps1.setString(1,newPass);
                ps1.setString(2,user_id);
                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this,"New Password succesfuly save");
                    index1 ref=new index1();
                    ref.setVisible(true);
                    dispose();

                }else{
                    JOptionPane.showMessageDialog(this,"user id and password not match");
                }

            }catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }
        // Need Updare Quries here for updateing

    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        String vehicle_id=(String)jComboBox1.getSelectedItem();
        JOptionPane.showMessageDialog(this,vehicle_id);
    
        
        if(vehicle_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"vehicle_id field Can not be left blank ");

        }
      
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from vehicle where vehicle_id=?");

                ps.setString(1,vehicle_id);
              
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

             //   jTextField13.setText("");
                             Admin_Home ref=new Admin_Home();
                             ref.setVisible(true);
                             dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        
             String vehicle_id=(String)jComboBox2.getSelectedItem();
            
             if(vehicle_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"vehicle_id field Can not be left blank ");

        }
      
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from recordtable where vehicle_id=?");

                ps.setString(1,vehicle_id);
              
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                jTextField14.setText("");
                             Admin_Home ref=new Admin_Home();
                             ref.setVisible(true);
                             dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }
            
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
    String feedbackid=(String)jComboBox4.getSelectedItem();
            if(feedbackid.equals(""))
        {
            JOptionPane.showMessageDialog(this,"feedbackid field Can not be left blank ");

        }
      
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from feedbacktable where feedbackid=?");

                ps.setString(1,feedbackid);
              
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //jTextField15.setText("");
                             Admin_Home ref=new Admin_Home();
                             ref.setVisible(true);
                 
                             dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:
        
            }
        
        
        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        
        
         String complain_id=(String)jComboBox3.getSelectedItem();
            if(complain_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Domplain_id field Can not be left blank ");

        }
      
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from complaintable where complain_id=?");

                ps.setString(1,complain_id);
              
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //jTextField15.setText("");
                             Admin_Home ref=new Admin_Home();
                             ref.setVisible(true);
                             dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:
        
            }
        
        
        
        
        
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

   String queryId=(String)jComboBox5.getSelectedItem();
            if(queryId.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Domplain_id field Can not be left blank ");

        }
      
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from queriestable where queryId=?");

                ps.setString(1,queryId);
              
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //jTextField15.setText("");
                             Admin_Home ref=new Admin_Home();
                             ref.setVisible(true);
                             dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:
        
            }
                
// TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
            jPanel11.setVisible(true);

    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

   String Vehicle_id=(String)jComboBox7.getSelectedItem();
   String cost=jTextField1.getText()+"Rs";

         if(cost.equals(""))
        {
            JOptionPane.showMessageDialog(this,"cost field Can not  left blank ");

        }
 else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("update vehicle set aproxcost=? where vehicle_id=?");                                

                ps.setString(1,cost);
                ps.setString(2,Vehicle_id);
              
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is Update succefully" );

                //jTextField15.setText("");
                             Admin_Home ref=new Admin_Home();
                             ref.setVisible(true);
                             dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:
        
            }         
         
         
   
   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
                //User_Home
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JPasswordField jPasswordField7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
