
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhishek
 */
public class Complain_Home1 extends javax.swing.JFrame {

    /**
     * Creates new form User_Home
     */
    public Complain_Home1() {
        initComponents();
        jTextField4.setText(index1.id);
          jTextField9.setText(index1.id);
            jTextField10.setText(index1.id);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPasswordField5 = new javax.swing.JPasswordField();
        jPasswordField7 = new javax.swing.JPasswordField();
        jPasswordField6 = new javax.swing.JPasswordField();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/welcome.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 590, 170));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/39420.gif"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 370, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User_id", "Vehicle_id", "Number", "Manufacture_Date", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 1000, 200));

        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, -1));

        jTabbedPane1.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/Candy-House-icon.png")), jPanel2); // NOI18N

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(0, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 255, 0));
        jLabel10.setText("       Create new Complain operator");
        jLabel10.setOpaque(true);
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 390, 54));

        jLabel18.setBackground(new java.awt.Color(51, 0, 51));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Operator Name");
        jLabel18.setOpaque(true);
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 150, 27));

        jLabel19.setBackground(new java.awt.Color(51, 0, 51));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Password");
        jLabel19.setOpaque(true);
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, -1));

        jLabel21.setBackground(new java.awt.Color(51, 0, 51));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("conf Password");
        jLabel21.setOpaque(true);
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 30));

        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 230, 27));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, -1));

        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("ADD");
        jButton5.setToolTipText("");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 105, -1));

        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Back");
        jButton6.setToolTipText("");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 119, -1));

        jLabel23.setBackground(new java.awt.Color(51, 0, 51));
        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Operator_id");
        jLabel23.setOpaque(true);
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 101, 27));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel8.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 210, 30));

        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel8.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 210, 30));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel3.setForeground(new java.awt.Color(153, 255, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, -1));

        jTabbedPane1.addTab("Add Operator", new javax.swing.ImageIcon(getClass().getResource("/gif/Devices-secure-card-icon.png")), jPanel1); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "User_id", "Vehicle_id", "Number", "Manufacture_Date", "Image"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 857, 120));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Order", new javax.swing.ImageIcon(getClass().getResource("/Finance-Purchase-Order-icon.png")), jPanel3); // NOI18N

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(0, 51, 51));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 255, 0));
        jLabel25.setText("           Feedback Form");
        jLabel25.setOpaque(true);
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jLabel29.setBackground(new java.awt.Color(51, 0, 51));
        jLabel29.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("  Write your feedbak here :");
        jLabel29.setOpaque(true);
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 230, -1));

        jButton7.setBackground(new java.awt.Color(0, 51, 51));
        jButton7.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 153, 255));
        jButton7.setText("Submit");
        jButton7.setToolTipText("");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 105, -1));

        jButton8.setBackground(new java.awt.Color(0, 51, 51));
        jButton8.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 51, 51));
        jButton8.setText("Back");
        jButton8.setToolTipText("");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 119, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel10.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 370, 150));

        jLabel26.setBackground(new java.awt.Color(51, 0, 51));
        jLabel26.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("User id");
        jLabel26.setOpaque(true);
        jPanel10.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 101, 27));

        jTextField9.setOpaque(false);
        jTextField9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField9MouseClicked(evt);
            }
        });
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, 27));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Feedback", new javax.swing.ImageIcon(getClass().getResource("/Messages-icon.png")), jPanel4); // NOI18N

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(0, 51, 51));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 255, 0));
        jLabel27.setText("       Complain");
        jLabel27.setOpaque(true);
        jPanel11.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jLabel30.setBackground(new java.awt.Color(51, 0, 51));
        jLabel30.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("  Write your Complain here :");
        jLabel30.setOpaque(true);
        jPanel11.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 230, -1));

        jButton9.setBackground(new java.awt.Color(0, 51, 51));
        jButton9.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 102, 255));
        jButton9.setText("Submit");
        jButton9.setToolTipText("");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 105, -1));

        jButton10.setBackground(new java.awt.Color(0, 51, 51));
        jButton10.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 51, 51));
        jButton10.setText("Back");
        jButton10.setToolTipText("");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 119, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jPanel11.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 370, 150));

        jLabel28.setBackground(new java.awt.Color(51, 0, 51));
        jLabel28.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("User id");
        jLabel28.setOpaque(true);
        jPanel11.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 101, 27));

        jTextField10.setOpaque(false);
        jTextField10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField10MouseClicked(evt);
            }
        });
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, 27));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Complaint", new javax.swing.ImageIcon(getClass().getResource("/msg-2-icon.png")), jPanel5); // NOI18N

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(0, 51, 51));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 255, 0));
        jLabel31.setText("               Quries  ?");
        jLabel31.setOpaque(true);
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 44, 289, 60));

        jLabel32.setBackground(new java.awt.Color(51, 0, 51));
        jLabel32.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("  Write your Query here :");
        jLabel32.setOpaque(true);
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, -1));

        jButton11.setBackground(new java.awt.Color(0, 51, 51));
        jButton11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 102, 255));
        jButton11.setText("Submit");
        jButton11.setToolTipText("");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 105, -1));

        jButton12.setBackground(new java.awt.Color(0, 51, 51));
        jButton12.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 51, 51));
        jButton12.setText("Back");
        jButton12.setToolTipText("");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 119, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane6.setViewportView(jTextArea3);

        jPanel12.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 370, 150));

        jLabel33.setBackground(new java.awt.Color(51, 0, 51));
        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("User id");
        jLabel33.setOpaque(true);
        jPanel12.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 101, 27));

        jTextField11.setOpaque(false);
        jTextField11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField11MouseClicked(evt);
            }
        });
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, 27));

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 810, 440));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Query", new javax.swing.ImageIcon(getClass().getResource("/help-file-icon.png")), jPanel6); // NOI18N

        jPanel7.setOpaque(false);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(0, 51, 51));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 255, 0));
        jLabel34.setText("       Change Password");
        jLabel34.setOpaque(true);
        jPanel13.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jLabel37.setBackground(new java.awt.Color(51, 0, 51));
        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Password");
        jLabel37.setOpaque(true);
        jPanel13.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 30));

        jLabel38.setBackground(new java.awt.Color(51, 0, 51));
        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("New Password");
        jLabel38.setOpaque(true);
        jPanel13.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, -1));

        jLabel39.setBackground(new java.awt.Color(51, 0, 51));
        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Conf Password");
        jLabel39.setOpaque(true);
        jPanel13.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 160, -1));

        jTextField12.setOpaque(false);
        jTextField12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField12MouseClicked(evt);
            }
        });
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel13.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 230, 27));

        jPasswordField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField5ActionPerformed(evt);
            }
        });
        jPanel13.add(jPasswordField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 220, 30));

        jPasswordField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField7ActionPerformed(evt);
            }
        });
        jPanel13.add(jPasswordField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 210, 30));

        jPasswordField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField6ActionPerformed(evt);
            }
        });
        jPanel13.add(jPasswordField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 220, 30));

        jButton13.setBackground(new java.awt.Color(0, 51, 51));
        jButton13.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 51, 51));
        jButton13.setText("Update");
        jButton13.setToolTipText("");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 105, -1));

        jButton14.setBackground(new java.awt.Color(0, 51, 51));
        jButton14.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 51, 51));
        jButton14.setText("Back");
        jButton14.setToolTipText("");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 119, -1));

        jLabel40.setBackground(new java.awt.Color(51, 0, 51));
        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("User id");
        jLabel40.setOpaque(true);
        jPanel13.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 101, 27));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 1356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(200, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Password", new javax.swing.ImageIcon(getClass().getResource("/password-icon_1.png")), jPanel7); // NOI18N

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car-share-multiple-people-animated.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, -30, 620, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Car-Share - 19 Users Infographic - Wide.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -290, 960, 940));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("Help", new javax.swing.ImageIcon(getClass().getResource("/Help-icon.png")), jPanel9); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1360, 590));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/switch-turn-off-icon.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 110, 110));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setForeground(new java.awt.Color(153, 255, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bikes.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1410, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed

        
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            
        String operator_id=jTextField4.getText();
        String operator_name=jTextField5.getText();
        String Vehicle_id=jTextField5.getText();
     
        String password=new String(jPasswordField1.getPassword());
        String cmfpassword=new String(jPasswordField2.getPassword());
//String password=new String(jPasswordField4.getPassword());
          if(operator_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_id field Can not be left blank ");
        
        }
       else if(operator_name.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_name Can not be left blank ");
        
        }
   else if(password.equals(""))
        {
        JOptionPane.showMessageDialog(this,"password field Can not be left blank ");
        
        }
      else if(cmfpassword.equals(""))
        {
        JOptionPane.showMessageDialog(this,"cmfpassword field Can not be left blank ");
        
        } 
   
          

// char[] ch=jPasswordField3.getPassword();
        //String password=new String(ch);
      else{ 
      /*  try{
            
           // Class.forName("com.mysql.jdbc.Driver");
              Class.forName("com.mysql.jdbc.Driver");
            //"jdbc:mysql://localhost:3306/scoter","root","root"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into uesr (?,?,?,?,?)");
     
        ps.setString(1,user_id);
        ps.setString(2,name);
       ps.setString(3,email);
       ps.setString(4,address);
       ps.setString(5,password);
    
       ps.executeUpdate();
       
       
          
             JOptionPane.showMessageDialog(this,"Sign up  Now login again" );
          
             index1 inf=new index1();
             setVisible(true);
             dispose();
             
             
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }*/
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked

        String operator_id=jTextField4.getText();
        String operator_name=jTextField5.getText();
        String Vehicle_id=jTextField5.getText();
     
        String password=new String(jPasswordField1.getPassword());
        String cmfpassword=new String(jPasswordField2.getPassword());
//String password=new String(jPasswordField4.getPassword());
          if(operator_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_id field Can not be left blank ");
        
        }
       else if(operator_name.equals(""))
        {
        JOptionPane.showMessageDialog(this,"operator_name Can not be left blank ");
        
        }
   else if(password.equals(""))
        {
        JOptionPane.showMessageDialog(this,"password field Can not be left blank ");
        
        }
      else if(cmfpassword.equals(""))
        {
        JOptionPane.showMessageDialog(this,"cmfpassword field Can not be left blank ");
        
        } 
   
          

// char[] ch=jPasswordField3.getPassword();
        //String password=new String(ch);
      else{ 
      /*  try{
            
           // Class.forName("com.mysql.jdbc.Driver");
              Class.forName("com.mysql.jdbc.Driver");
            //"jdbc:mysql://localhost:3306/scoter","root","root"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into uesr (?,?,?,?,?)");
     
        ps.setString(1,user_id);
        ps.setString(2,name);
       ps.setString(3,email);
       ps.setString(4,address);
       ps.setString(5,password);
    
       ps.executeUpdate();
       
       
          
             JOptionPane.showMessageDialog(this,"Sign up  Now login again" );
          
             index1 inf=new index1();
             setVisible(true);
             dispose();
             
             
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }*/
      }   

        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked

                   
        String user_id=jTextField9.getText();
        String feedback=jTextArea1.getText();
      
          if(user_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"id field Can't  left blank ");
        
        }
       else if(feedback.equals(""))
        {
        JOptionPane.showMessageDialog(this,"feedback field Can't left blank ");
        
        }
  
      else{ 
      /*  try{
            
          
              Class.forName("com.mysql.jdbc.Driver");
          
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into feedback (?,?)");
     
        ps.setString(1,user_id);
        ps.setString(2,name);
       ps.setString(3,email);
    
             
             
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }*/
      }
        
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9MouseClicked

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
                     
        String user_id=jTextField10.getText();
        String complain=jTextArea2.getText();
      
          if(user_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"id field Can't  left blank ");
        
        }
       else if(complain.equals(""))
        {
        JOptionPane.showMessageDialog(this,"Complain field Can't left blank ");
        
        }
  
      else{ 
      /*  try{
            
          
              Class.forName("com.mysql.jdbc.Driver");
          
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into feedback (?,?)");
     
        ps.setString(1,user_id);
        ps.setString(2,name);
       ps.setString(3,email);
    
             
             
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }*/
      }
        
        
        
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10MouseClicked

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        
            String user_id=jTextField10.getText();
        String query=jTextArea2.getText();
      
          if(user_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"id field Can't  left blank ");
        
        }
       else if(query.equals(""))
        {
        JOptionPane.showMessageDialog(this,"query field Can't left blank ");
       
        }
  
      else{ 
      /*  try{
                      
              Class.forName("com.mysql.jdbc.Driver");
          
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("insert into feedback (?,?)");
     
        ps.setString(1,user_id);
        ps.setString(2,name);
       ps.setString(3,email);
                           
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }*/
      }
        
        
        
        
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTextField11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11MouseClicked

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12MouseClicked

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jPasswordField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField5ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked

        
        
        String user_id=jTextField12.getText();
        String oldPass=new String(jPasswordField5.getPassword());      
        String newPass=new String(jPasswordField6.getPassword());      
        String confPass=new String(jPasswordField7.getPassword());      
        
        
        if(user_id.equals(""))
        {
        JOptionPane.showMessageDialog(this,"id field Can't  left blank ");
        
        }
       else if(oldPass.equals(""))
        {
        JOptionPane.showMessageDialog(this,"oldPass field Can't left blank ");
               }
         else if(newPass.equals(""))
        {
        JOptionPane.showMessageDialog(this,"newPass field Can't left blank ");
       
        }
    else if(confPass.equals(newPass))
        {
        JOptionPane.showMessageDialog(this,"Old and new password should be same!! ");
       
        }
  
       else if(confPass.equals(""))
        {
        JOptionPane.showMessageDialog(this,"confPass field Can't left blank ");
       
        }
  
  
      else{ 
      /*  try{
                      
              Class.forName("com.mysql.jdbc.Driver");
          
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");  
             
       PreparedStatement ps=con.prepareStatement("update password (?,?)");
     
        ps.setString(1,user_id);
        ps.setString(2,name);
       ps.setString(3,email);
                           
        }catch(Exception ex)
        {
        ex.printStackTrace();
        }*/
      }
        // Need Updare Quries here for updateing 
        
        
        
        
        
        
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jPasswordField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField6ActionPerformed

    private void jPasswordField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField7ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int output=JOptionPane.showConfirmDialog(this,"Do You Want To SignOut");
        
        if(output==0){
            index1 ref=new index1();
            ref.setVisible(true);
            dispose();
                }
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
                //User_Home
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField5;
    private javax.swing.JPasswordField jPasswordField6;
    private javax.swing.JPasswordField jPasswordField7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
