
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhishek
 */
public class ManagerHomeNew extends javax.swing.JFrame {

    /**
     * Creates new form User_Home
     */
    public ManagerHomeNew() {
        initComponents();
       
         jPanel11.setVisible(false);
        
              try{
       
    //       Class.forName("com.mysql.jdbc.Driver");
  //     Connection con=DriverManager.getConnection("jdbc:mysql:\\localhost:3306\scoter","root","root");
      Class.forName("com.mysql.jdbc.Driver"); 
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");     
       
            
            
               PreparedStatement ps=con.prepareStatement("select * from vehicle");
           ResultSet rs=ps.executeQuery();
           //DefaultTableModel
           DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
           while(rs.next()){
           
            Object obj[]={rs.getString(2),rs.getString(1),rs.getString(3),rs.getString(4),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(10),rs.getString(9)}; 
         // jComboBox1.setModel((ComboBoxModel)rs.getString(2) );
            //jComboBox1.setModel(new ComboBoxModel<rs>);
         jComboBox1.addItem(rs.getString(1));
               jComboBox7.addItem(rs.getString(1));
            dtm.addRow(obj);
           }
           
           
               PreparedStatement ps1=con.prepareStatement("select * from recordtable");   
          ResultSet rs1=ps1.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm1=(DefaultTableModel)jTable2.getModel();
           while(rs1.next()){
           
            Object obj1[]={rs1.getString(1),rs1.getString(2),rs1.getString(3),rs1.getString(4),rs1.getString(5)}; 
        jComboBox2.addItem(rs1.getString(3));
            // jComboBox1.setModel((ComboBoxModel)rs.getString(2) );
             dtm1.addRow(obj1);
           } 
     
           
            PreparedStatement ps2=con.prepareStatement("select * from feedbacktable");   
          ResultSet rs2=ps2.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm2=(DefaultTableModel)jTable6.getModel();
           while(rs2.next()){
           
          Object obj3[]={rs2.getString(3),rs2.getString(1),rs2.getString(2)}; 
             dtm2.addRow(obj3);
             jComboBox4.addItem(rs2.getString(3));
             
           }
           
          
             PreparedStatement ps3=con.prepareStatement("select * from complaintable");   
          ResultSet rs3=ps3.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm3=(DefaultTableModel)jTable4.getModel();
           while(rs3.next()){
           
            Object obj3[]={rs3.getString(3),rs3.getString(1),rs3.getString(2)}; 
             dtm3.addRow(obj3);
             jComboBox3.addItem(rs3.getString(3));
             
           }
           
         
           
    PreparedStatement ps4=con.prepareStatement("select * from queriestable");   
          ResultSet rs4=ps4.executeQuery();
           //DefaultTableModel
      DefaultTableModel dtm4=(DefaultTableModel)jTable7.getModel();
           while(rs4.next()){
           
             Object obj4[]={rs4.getString(3),rs4.getString(1),rs4.getString(2)}; 
             dtm4.addRow(obj4);
             jComboBox5.addItem(rs4.getString(3));
             
           }
    
       }
       catch(Exception Ex)
       {
          Ex.printStackTrace();
       }
            
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel11 = new javax.swing.JPanel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton16 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField14 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 51));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/39420.gif"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 140));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton20.setBackground(new java.awt.Color(0, 51, 51));
        jButton20.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(204, 255, 51));
        jButton20.setText("Set Charges");
        jButton20.setToolTipText("");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 220, 40));

        jButton15.setBackground(new java.awt.Color(0, 0, 102));
        jButton15.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(204, 255, 51));
        jButton15.setText("Delet Records");
        jButton15.setToolTipText("");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 300, 40));

        jScrollPane1.setOpaque(false);

        jTable1.setBackground(new java.awt.Color(0, 0, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 51)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User_id", "Vehicle_id", "Vehicle_name", "Vehicle Number", "ManufactureDate", "contanctNumber", "Availblity time", "Avaliblity Date", "Aprox_Charges"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1150, 200));

        jComboBox1.setBackground(new java.awt.Color(0, 0, 153));
        jComboBox1.setForeground(new java.awt.Color(204, 255, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---select---", " " }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 230, 40));

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox7.setBackground(new java.awt.Color(0, 153, 255));
        jComboBox7.setForeground(new java.awt.Color(255, 255, 153));
        jComboBox7.setSelectedItem(jTable1);
        jPanel11.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/coin-add-icon.png"))); // NOI18N
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 50, 30));

        jButton1.setText("Save Charges");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 150, 50));

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setForeground(new java.awt.Color(153, 255, 51));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 30));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 540, 80));

        jLabel5.setForeground(new java.awt.Color(153, 255, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1344, -1));

        jTabbedPane1.addTab("Home", new javax.swing.ImageIcon(getClass().getResource("/Candy-House-icon.png")), jPanel2); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---select---", " " }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 260, 40));

        jButton16.setBackground(new java.awt.Color(0, 51, 51));
        jButton16.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 51, 51));
        jButton16.setText("Delet Records");
        jButton16.setToolTipText("");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 300, 40));

        jScrollPane3.setOpaque(false);

        jTable2.setBackground(new java.awt.Color(0, 102, 153));
        jTable2.setForeground(new java.awt.Color(153, 255, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seller_id", "Coustomerid", "vehicle_id", "date", "time", "vihecle_number"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jScrollPane4.setViewportView(jScrollPane3);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 930, 300));

        jTextField14.setToolTipText("Enter The user to delet the record");
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 260, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View Order", new javax.swing.ImageIcon(getClass().getResource("/Finance-Purchase-Order-icon.png")), jPanel3); // NOI18N

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton17.setBackground(new java.awt.Color(0, 51, 51));
        jButton17.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 51, 51));
        jButton17.setText("Delet Records");
        jButton17.setToolTipText("");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 300, 40));

        jLabel25.setBackground(new java.awt.Color(0, 51, 51));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 255, 0));
        jLabel25.setText("           Feedback Form");
        jLabel25.setOpaque(true);
        jPanel10.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jScrollPane14.setOpaque(false);

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feedbaack_id", "User_id", "feedback"
            }
        ));
        jScrollPane14.setViewportView(jTable6);

        jScrollPane13.setViewportView(jScrollPane14);

        jPanel10.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 720, 190));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 50));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View Feedback", new javax.swing.ImageIcon(getClass().getResource("/Messages-icon.png")), jPanel4); // NOI18N

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton18.setBackground(new java.awt.Color(0, 51, 51));
        jButton18.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 51, 51));
        jButton18.setText("Delet Records");
        jButton18.setToolTipText("");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 300, 40));

        jLabel26.setBackground(new java.awt.Color(0, 51, 51));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 255, 0));
        jLabel26.setText("          View Complain");
        jLabel26.setOpaque(true);
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 21, 289, 54));

        jScrollPane10.setOpaque(false);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Complain_id", "User_id", "complain"
            }
        ));
        jScrollPane10.setViewportView(jTable4);

        jScrollPane9.setViewportView(jScrollPane10);

        jPanel14.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 720, 190));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel14.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 50));

        jPanel5.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View  Complaint", new javax.swing.ImageIcon(getClass().getResource("/msg-2-icon.png")), jPanel5); // NOI18N

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setBackground(new java.awt.Color(0, 51, 51));
        jButton19.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 51, 51));
        jButton19.setText("Delet Records");
        jButton19.setToolTipText("");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 300, 40));

        jLabel29.setBackground(new java.awt.Color(0, 51, 51));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 255, 0));
        jLabel29.setText("          View Queries ");
        jLabel29.setOpaque(true);
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 289, 54));

        jScrollPane16.setOpaque(false);

        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Queryid", "User_id", "Query"
            }
        ));
        jScrollPane16.setViewportView(jTable7);

        jScrollPane15.setViewportView(jScrollPane16);

        jPanel15.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 720, 190));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel15.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 230, 50));

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 810, 440));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1356, -1));

        jTabbedPane1.addTab("View Query", new javax.swing.ImageIcon(getClass().getResource("/help-file-icon.png")), jPanel6); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1360, 590));

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("    Welcome  Manager ");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 270, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/rakib-bike.gif"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 610, 150));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/switch-turn-off-icon.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 110, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gif/printer-icon.png"))); // NOI18N
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 120, 70));

        jLabel2.setBackground(new java.awt.Color(153, 255, 153));
        jLabel2.setForeground(new java.awt.Color(153, 255, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bikes.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1410, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int output=JOptionPane.showConfirmDialog(this,"Do You Want To SignOut");
        
        if(output==0){
            index1 ref=new index1();
            ref.setVisible(true);
            dispose();
                }
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        String queryId=(String)jComboBox5.getSelectedItem();
        if(queryId.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Domplain_id field Can not be left blank ");

        }

        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from queriestable where queryId=?");

                ps.setString(1,queryId);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //jTextField15.setText("");
                Admin_Home ref=new Admin_Home();
                ref.setVisible(true);
                dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:

        String complain_id=(String)jComboBox3.getSelectedItem();
        if(complain_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Domplain_id field Can not be left blank ");

        }

        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from complaintable where complain_id=?");

                ps.setString(1,complain_id);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //jTextField15.setText("");
                Admin_Home ref=new Admin_Home();
                ref.setVisible(true);
                dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:

        }

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String feedbackid=(String)jComboBox4.getSelectedItem();
        if(feedbackid.equals(""))
        {
            JOptionPane.showMessageDialog(this,"feedbackid field Can not be left blank ");

        }

        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from feedbacktable where feedbackid=?");

                ps.setString(1,feedbackid);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //jTextField15.setText("");
                Admin_Home ref=new Admin_Home();
                ref.setVisible(true);

                dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:

        }

    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        String vehicle_id=(String)jComboBox2.getSelectedItem();

        if(vehicle_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"vehicle_id field Can not be left blank ");

        }

        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from recordtable where vehicle_id=?");

                ps.setString(1,vehicle_id);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                jTextField14.setText("");
                Admin_Home ref=new Admin_Home();
                ref.setVisible(true);
                dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        String vehicle_id=(String)jComboBox1.getSelectedItem();
        JOptionPane.showMessageDialog(this,vehicle_id);

        if(vehicle_id.equals(""))
        {
            JOptionPane.showMessageDialog(this,"vehicle_id field Can not be left blank ");

        }

        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("delete from vehicle where vehicle_id=?");

                ps.setString(1,vehicle_id);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is deleted succefully" );

                //   jTextField13.setText("");
                Admin_Home ref=new Admin_Home();
                ref.setVisible(true);
                dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String Vehicle_id=(String)jComboBox7.getSelectedItem();
        String cost=jTextField1.getText();

        if(cost.equals(""))
        {
            JOptionPane.showMessageDialog(this,"cost field Can not  left blank ");

        }
        else{
            try{

                Class.forName("com.mysql.jdbc.Driver");

                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/scoter","root","root");

                PreparedStatement ps=con.prepareStatement("update vehicle set aproxcost=? where vehicle_id=?");

                ps.setString(1,cost);
                ps.setString(2,Vehicle_id);

                ps.executeUpdate();

                JOptionPane.showMessageDialog(this,"Record is Update succefully" );

                //jTextField15.setText("");
                Admin_Home ref=new Admin_Home();
                ref.setVisible(true);
                dispose();
            }catch(Exception ex)
            {
                ex.printStackTrace();
            }        // TODO add your handling code here:

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        jPanel11.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerHomeNew().setVisible(true);
                //User_Home
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    // End of variables declaration//GEN-END:variables
}
